# Información general
site_name: 'Diseño web'
site_description: 'Apuntes sobre diseño web'
site_author: 'Raul Jesus Lopez'
site_url: http://www.web.rauljesus.com

# Repositorio
repo_name: 'Ver en GitHub'
repo_url: 'https://github.com/la9una/web'

# Copyright
#copyright: '2017 - Raul Jesus Lopez'

# Tema
theme: null
theme_dir: 'themes/material'

# Opciones
extra:
  palette:
    primary: 'blue grey'
    accent: 'blue grey'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  social:
#    - type: 'github'
#      link: 'https://github.com/la9una'
    - type: 'twitter'
      link: 'https://twitter.com/la9una'
#    - type: 'linkedin'
#      link: 'https://de.linkedin.com/in/john-doe'
#    - type: 'facebook'
#      link: 'https://www.facebook.com/rauljesuslopez'
  disqus: 'rauljesuscom'

# Google Analytics
google_analytics:
  - 'UA-98408177-1'
  - 'auto'

# Extensions
markdown_extensions:
  - pymdownx.arithmatex
  - admonition
  - codehilite(guess_lang=false)
  - toc(permalink=true)
  - footnotes
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg

# Extras
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

# Páginas
pages: 
- Inicio: index.md
- ¿Qué es?:
    - El diseño web: 'introduccion/por_que_gnu_linux.md'
    - Frontend vs Backend: 'introduccion/por_que_gnu_linux.md'
- Fundamentos de HTML:
    - Estructura del documento: 'html/archivosCarpetas.md'
    - Compresión y descompresión: 'html/compresion.md'
    - El editor nano: 'html/nano.md'
- Fundamentos de CSS: 
    - Búsquedas: 'cssFundamentos/busquedas.md'
    - Búsquedas: 'cssFundamentos/busquedas.md'