# Información general
site_name: 'Diseño web'
site_description: 'Apuntes sobre diseño web'
site_author: 'Raul Jesus Lopez'
site_url: http://rauljesus.xyz/web

# Repositorio
repo_name: 'Ver en GitHub'
repo_url: 'https://github.com/la9una/web'

# Copyright
copyright: 'Raul Jesus Lopez'

# Tema
theme:
  name: 'material'
  language: 'es'
  icon:
 #   logo: material/library
    logo: fontawesome/solid/graduation-cap
    repo: fontawesome/brands/git-alt
  palette:
    primary: 'teal'
    accent: 'teal'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  feature:
    tabs: true

# Extra
extra:
  disqus: 'rauljesus-xyz'
  manifest: manifest.webmanifest
  social:
    - icon: fontawesome/brands/twitter
      link: 'https://twitter.com/la9una'
    - icon: fontawesome/brands/facebook-f
      link: 'https://www.facebook.com/rauljesuslopez'
    - icon: fontawesome/brands/github
      link: 'https://github.com/la9una'

# Extensiones
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML


plugins:
  - search # necessary for search to work
  - git-revision-date-localized:
      type: date

######################################################################
### DOCUMENTACIÓN ####################################################
######################################################################
nav: 

# Documentación sobre HTML
- Inicio: index.md
#- ¿Qué es?:
#    - El diseño web: 'disenoIntroduccion/index.md'
#    - Frontend vs Backend: 'introduccion/index.md'
#- Fundamentos de HTML:
#    - Estructura del documento: 'html/archivosCarpetas.md'
#    - Compresión y descompresión: 'html/compresion.md'
#    - El editor nano: 'html/nano.md'
#- Fundamentos de CSS: 
#    - Búsquedas: 'cssFuentes/busquedas.md'
#    - Búsquedas: 'cssFuentes/busquedas.md'
- Diseño web: 
    - Introducción: 'disenoWeb/index.md'
    - Herramientas web: 'disenoWeb/herramientas.md'
#    - Mobile first: 'disenoWeb/work.md'
#    - Responsive design: 'disenoWeb/work.md'
#    - Usabilidad: 'disenoWeb/work.md'
#    - Accesibilidad: 'disenoWeb/work.md'
#- Fundamentos de HTML: 
#    - Introducción: 'htmlFundamentos/index.md'
#    - Descubriendo HTML: 'htmlFundamentos/descubriendoHTML.md'
#- CSS básico:
#    - Colores: 'cssColores/index.md'
#    - Texto: 'cssTexto/index.md'
- Fundamentos HTML:
    - ¿Qué aprenderemos?: 'htmlFundamentos/Propuesta.md'
    - Estructura HTML: 'htmlFundamentos/EstructuraDocumento.md'
    - Títulos y párrafos: 'htmlFundamentos/TitularesParrafos.md'
    - Listas y tablas: 'htmlFundamentos/ListasTablas.md'
    - Enlaces: 'htmlFundamentos/Enlaces.md'
    - Imágenes: 'htmlFundamentos/Imagenes.md'
    - Formularios: 'htmlFundamentos/Formularios.md'
    - Tipos de elementos: 'htmlFundamentos/ElementosBloqueLinea.md'
    - Web semántica: 'htmlFundamentos/WebSemantica.md'
#    - Anexo: 'htmlFundamentos/anexo.md'

# Documentación sobre CSS
- Fundamentos de CSS:
    - Introducción: 
      - ¿Qué es CSS?: 'cssFundamentos/introCSS.md'
      - Primeros pasos: 'cssFundamentos/introGettingStarted.md'
      - Sintaxis: 'cssFundamentos/introSintax.md'
      - Ejercicios: 'cssFundamentos/introlExercises.md'
    - Valores y unidades: 
      - Introducción: 'cssFundamentos/units.md'
      - Numéricas: 'cssFundamentos/unitsNumbers.md'
      - Color: 'cssFundamentos/unitsColors.md'
      - Porcentaje y funciones: 'cssFundamentos/unitsPercent.md'
      - Ejercicios: 'cssFundamentos/unitsExercises.md'
    - Modelo de caja: 
      - Definición: 'cssFundamentos/boxModel.md'
      - Bordes: 'cssFundamentos/boxModelBorder.md'
      - Márgenes: 'cssFundamentos/boxModelMargins.md'
      - Forma abreviada: 'cssFundamentos/boxModelShorthand.md'
      - Posicionamiento: 'cssFundamentos/boxModelPosition.md'
      - Ejercicios: 'cssFundamentos/boxModelExercises.md'
    - Tipografía: 
      - Reseña histórica: 'cssFuentes/fuentesIndex.md'
      - Propiedades de fuente: 'cssFuentes/fuentesPropiedades.md'
      - Formato de texto: 'cssFuentes/fuentesFormato.md'
      - Usando webfonts: 'cssFuentes/fuentesWebFonts.md'
      - Elegir tipografía: 'cssFuentes/fuentesTipografia.md'
      - Ejercicios: 'cssFuentes/fuentesEjercicios.md'
- Bootstrap:
    - Introducción: 'bootstrap/index.md'
    - Primeros pasos: 'bootstrap/primerosPasos.md'
    - Sistema de rejilla: 
        - Introducción: 'bootstrap/gridIntroduccion.md'
        - Reglas: 'bootstrap/gridReglas.md'   
        - Diseño adaptable: 'bootstrap/gridResponsive.md'
    - Alineación de columnas: 
        - Flexbox: 'bootstrap/alignci.md'
        - Eje principal: 'bootstrap/alignch.md'
        - Eje secundario: 'bootstrap/aligncv.md'
    - Ejercicios: 'bootstrap/ejercicios.md'


