# Información general
site_name: 'Diseño web'
site_description: 'Apuntes sobre diseño web'
site_author: 'Raul Jesus Lopez'
site_url: http://rauljesus.xyz/web

# Repositorio
repo_name: 'Ver en GitHub'
repo_url: 'https://github.com/la9una/web'

# Copyright
copyright: '2018 &nbsp; Raul Jesus Lopez'

# Tema
theme:
  name: 'material'
  custom_dir: 'material'
  language: 'es'
  palette:
    primary: 'blue grey'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
#  feature:
#    tabs: true

# Extra
extra:
  search:
    language: 'es, en'
  disqus: 'rauljesus-xyz'
  social:
    - type: 'twitter'
      link: 'https://twitter.com/la9una'
    - type: 'facebook'
      link: 'https://www.facebook.com/rauljesuslopez'
    - type: 'github'
      link: 'https://github.com/la9una'
#    - type: 'linkedin'
#      link: 'https://de.linkedin.com/in/john-doe'

## CSS Adicional
extra_css:
  - 'stylesheets/extra.css'

# Extensiones
markdown_extensions:
  - admonition
#  - codehilite(guess_lang=false,linenums=true)
  - codehilite(guess_lang=false)
  - toc:
      permalink: true
  - footnotes
  - pymdownx.critic
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg

######################################################################
### DOCUMENTACIÓN ####################################################
######################################################################
pages: 

# Documentación sobre HTML
- Inicio: index.md
#- ¿Qué es?:
#    - El diseño web: 'disenoIntroduccion/index.md'
#    - Frontend vs Backend: 'introduccion/index.md'
#- Fundamentos de HTML:
#    - Estructura del documento: 'html/archivosCarpetas.md'
#    - Compresión y descompresión: 'html/compresion.md'
#    - El editor nano: 'html/nano.md'
#- Fundamentos de CSS: 
#    - Búsquedas: 'cssFuentes/busquedas.md'
#    - Búsquedas: 'cssFuentes/busquedas.md'
- Diseño web: 
    - Introducción: 'disenoWeb/index.md'
    - Herramientas web: 'disenoWeb/herramientas.md'
#    - Mobile first: 'disenoWeb/work.md'
#    - Responsive design: 'disenoWeb/work.md'
#    - Usabilidad: 'disenoWeb/work.md'
#    - Accesibilidad: 'disenoWeb/work.md'
#- Fundamentos de HTML: 
#    - Introducción: 'htmlFundamentos/index.md'
#    - Descubriendo HTML: 'htmlFundamentos/descubriendoHTML.md'
#- CSS básico:
#    - Colores: 'cssColores/index.md'
#    - Texto: 'cssTexto/index.md'
- Fundamentos HTML:
    - Primeros pasos: 'htmlFundamentos/PrimerosPasosHTML.md'
    - Estructura HTML: 'htmlFundamentos/EstructuraDocumento.md'
    - Títulos y párrafos: 'htmlFundamentos/TitularesParrafos.md'
    - Listas y tablas: 'htmlFundamentos/ListasTablas.md'
    - Enlaces: 'htmlFundamentos/Enlaces.md'
    - Imágenes: 'htmlFundamentos/Imagenes.md'
    - Formularios: 'htmlFundamentos/Formularios.md'
    - Tipos de elementos: 'htmlFundamentos/ElementosBloqueLinea.md'
    - Web semántica: 'htmlFundamentos/WebSemantica.md'

# Documentación sobre CSS
- Fundamentos de CSS:
    - Introducción: 'cssFundamentos/index.md'
    - Primeros pasos: 'cssFundamentos/gettingstarted.md'
    - Selectores: 'cssFundamentos/selectores.md'
    - Valores y unidades: 
      - Introducción: 'cssFundamentos/units.md'
      - Numéricas: 'cssFundamentos/unitsNumbers.md'
      - Color: 'cssFundamentos/unitsColors.md'
      - Porcentaje y funciones: 'cssFundamentos/unitsPercent.md'
    - Modelo de caja: 
        - Definición: 'cssBoxModel/boxmodel.md'
        - Posicionamiento: 'cssBoxModel/position.md'
    - Tipografía: 
      - Reseña histórica: 'cssFuentes/fuentesIndex.md'
      - Propiedades de fuente: 'cssFuentes/fuentesPropiedades.md'
      - Formato de texto: 'cssFuentes/fuentesFormato.md'
      - Usando webfonts: 'cssFuentes/fuentesWebFonts.md'
      - Elegir tipografía: 'cssFuentes/fuentesTipografia.md'
    - Ejercicios: 'cssFundamentos/ejercicios.md'
#    - Fondos: 'cssFondos/index.md'
#    - Listas: 'cssListas/index.md'
#    - Tablas: 'cssColores/index.md'
#    - Formularios: 'cssFormularios/index.md'
#    - Imágenes: 'cssImagenes/index.md'
#    - Videos: 'cssVideos/index.md'
#- Maquetado CSS: 
#    - Prototipado: 'disenoPrototipado/index.md'
#    - Modelo de caja: 'cssBoxmodel/index.md'
#    - Posicionamiento: 'cssColores/index.md'
#    - Media Queries: 'cssColores/index.md'
#    - Viewport: 'cssColores/index.md'
#    - Flexbox: 'cssFlexbox/index.md'
#- Efectos CSSS: 
#    - Transciciones: 'cssEfectos/index.md'
#- Frameworks CSS: 
#    - Función: 'cssFrameworks/index.md'
- Bootstrap:
    - Introducción: 'bootstrap/index.md'
    - Primeros pasos: 'bootstrap/primerosPasos.md'
    - Sistema de rejilla: 
        - Introducción: 'bootstrap/gridIntroduccion.md'
        - Reglas: 'bootstrap/gridReglas.md'   
        - Diseño adaptable: 'bootstrap/gridResponsive.md'  
    - Ejercicios: 'bootstrap/ejercicios.md'

- Control de versiones: 
    - ¿Qué es Git?: 'git/index.md'
    - Entornos distribuidos: 'git/flujoEntornosDistribuidos.md'
    - Instalación de Git: 'git/instalacion.md'
    - Configuración inicial: 'git/configuracionInicial.md'
    - Los tres estados: 'git/losTresEstados.md'
    - Inicializando repositorio local: 'git/repositorioLocal.md'
    - Git en el servidor: 'git/servidorGit.md'
    - Trabajando con remotos: 'git/trabajandoConRemotos.md'
    - Ramas: 'git/ramas.md'
    - Deshaciendo cambios: 'git/deshaciendoCambios.md'
    - Otros comandos: 'git/otrosComandosGit.md'
    - Ejemplo de uso de git: 'git/ejemploGit.md'

